import { Tokens } from "./tokens";

export const tokenSymbol: { [key in Tokens]: string } = {
  [Tokens.Moon]: "MOON",
  [Tokens.USDCE]: "USDC.e",
  [Tokens.USDC]: "USDC",
  [Tokens.WETH]: "WETH",
  [Tokens.WBTC]: "WBTC",
  [Tokens.USDT]: "USDT",
  [Tokens.SNX]: "SNX",
  [Tokens.WSTETH]: "wstETH",
  [Tokens.DAI]: "DAI",
  [Tokens.GUARD]: "GUARD",
  [Tokens.ETH]: "ETH",
  [Tokens.MTK]: "MTK",
  [Tokens.FUD]: "FUD",
  [Tokens.FOMO]: "FOMO",
  [Tokens.ALPHA]: "ALPHA",
  [Tokens.KEK]: "KEK",
  [Tokens.GLTR]: "GLTR",
  [Tokens.STIME]: "STIME",
  [Tokens.ARB]: "ARB",
  [Tokens.WWINR]: "WWINR",
  [Tokens.WINR]: "WINR",
  [Tokens.VWINR]: "VWINR",
  [Tokens.USDE]: "USDe",
  [Tokens.MAGIC]: "MAGIC",
  [Tokens.SUSDE]: "SUSDE",
  [Tokens.BOOP]: "BOOP",
  [Tokens.SPX]: "SPX",
  [Tokens.BRETT]: "BRETT",
  [Tokens.TOSHI]: "TOSHI",
  [Tokens.PEPE]: "PEPE",
  [Tokens.MOG]: "MOG",
  [Tokens.SHIB]: "SHIB",
};
